// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Category struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Customer struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	LastName string `json:"lastName"`
	Email    string `json:"email"`
}

type NewCategory struct {
	Name string `json:"name"`
}

type NewCustomer struct {
	Name     string `json:"name"`
	LastName string `json:"lastName"`
	Email    string `json:"email"`
}

type NewRoutine struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type NewRoutineSchedule struct {
	Routine string `json:"routine"`
	WeekDay string `json:"weekDay"`
}

type NewSession struct {
	Name      string `json:"name"`
	StartHour string `json:"startHour"`
	FinalHour string `json:"finalHour"`
	Period    string `json:"period"`
}

type NewWeekDay struct {
	Name       string `json:"name"`
	NumericDay int    `json:"numericDay"`
}

type Routine struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type RoutineSchedule struct {
	ID      string   `json:"id"`
	Routine *Routine `json:"routine"`
	WeekDay *WeekDay `json:"weekDay"`
}

type Session struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	StartHour string `json:"startHour"`
	FinalHour string `json:"finalHour"`
	Period    string `json:"period"`
}

type WeekDay struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	NumericDay int    `json:"numericDay"`
}
