// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Category struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Customer struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	LastName string `json:"lastName"`
	Email    string `json:"email"`
}

type NewCategory struct {
	Name string `json:"name"`
}

type NewCustomer struct {
	Name     string `json:"name"`
	LastName string `json:"lastName"`
	Email    string `json:"email"`
}

type NewRoutine struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type Routine struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}
